name: Main

on: [push, pull_request]

jobs:
  rchk:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    runs-on: ubuntu-latest
    env:
      NOT_CRAN: true
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/run-rchk@master
      # - uses: randy3k/actions/run-rchk@rchk
        with:
          apt: libgmp3-dev

  ubsan:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    runs-on: ubuntu-latest
    container: rocker/r-devel-ubsan-clang
    env:
      NOT_CRAN: true
    steps:
      - uses: actions/checkout@v1
      - name: Install gmp
        run: |
          apt-get update
          apt-get install libgmp3-dev -y
      - name: Install dependencies
        run: |
          RDscript -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://cloud.r-project.org')"
          RDscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Running Tests
        run: |
          RDscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual', '--timings'))"

  linux:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    strategy:
      matrix:
        r: [latest]
        # r: [3.5, latest, devel]
    runs-on: ubuntu-latest
    container: rocker/tidyverse:${{ matrix.r }}
    env:
      NOT_CRAN: true
    steps:
    - uses: actions/checkout@v1
    - name: Install gmp
      run: |
        apt-get update
        apt-get install libgmp3-dev -y
    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://cloud.r-project.org')"
        Rscript -e "remotes::install_deps(dependencies = TRUE)"
    - name: Running Tests
      run: |
        Rscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual', '--timings'))"

  macos:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    strategy:
      matrix:
        r: [latest]
        # r: [3.5, latest, devel]
    runs-on: macOS-latest
    env:
      NOT_CRAN: true
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - name: Install gmp
        run: brew install gmp
      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://cloud.r-project.org', type = 'mac.binary')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, type = 'mac.binary.el-capitan')"
      - name: Running Tests
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual', '--timings'))"
